#!/usr/bin/env bash
# Extract stock Biscuit non-GPU blobs from system.img into ignored vendor trees.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SYSTEM_IMG="${1:-$REPO_ROOT/workspace/extracted/biscuit-stock-272.6.4.1/system.img}"
LIST="$REPO_ROOT/sources/device_amazon_mt8163_common/proprietary-files.txt"
COMMON_OUT="$REPO_ROOT/workspace/vendor/amazon/mt8163-common"
BISCUIT_OUT="$REPO_ROOT/workspace/vendor/amazon/biscuit"
PROP="$COMMON_OUT/proprietary"
mkdir -p "$REPO_ROOT/workspace/tmp"
TMP="$(mktemp -d -p "$REPO_ROOT/workspace/tmp" extract-blobs.XXXXXXXXXX)"
trap 'rm -rf "$TMP"' EXIT

if [[ ! -f "$SYSTEM_IMG" ]]; then
  echo "ERROR: system.img not found: $SYSTEM_IMG" >&2
  echo "Run scripts/prepare-biscuit-stock-system-image.sh or pass a system.img path." >&2
  exit 1
fi
command -v 7z >/dev/null || { echo "ERROR: 7z required" >&2; exit 1; }

rm -rf "$COMMON_OUT" "$BISCUIT_OUT"
mkdir -p "$PROP" "$BISCUIT_OUT"

copy_files=()
while IFS= read -r entry; do
  entry="${entry%%#*}"
  entry="$(printf '%s' "$entry" | xargs)"
  [[ -z "$entry" ]] && continue

  src="${entry%%:*}"
  if [[ "$entry" == *:* ]]; then dst="${entry#*:}"; else dst="$src"; fi

  rm -rf "$TMP"/*
  # 7z may return non-zero on this ext4 image after extracting; trust the file.
  7z x -y -o"$TMP" "$SYSTEM_IMG" "$src" >/dev/null 2>&1 || true
  if [[ ! -f "$TMP/$src" ]]; then
    echo "ERROR: missing in system.img: $src" >&2
    exit 1
  fi
  mode=0644
  [[ "$dst" == "etc/audio_init.sh" ]] && mode=0755
  install -D -m "$mode" "$TMP/$src" "$PROP/$dst"
  copy_files+=("vendor/amazon/mt8163-common/proprietary/$dst:system/$dst")
done < "$LIST"

# Force software EGL. Stock has "0 1 mali" even though Biscuit is headless/no_gpu.
if [[ -f "$PROP/lib/egl/egl.cfg" ]]; then
  printf '0 0 android\n' > "$PROP/lib/egl/egl.cfg"
fi

# Raise the TLV320ADC3101 analog mic PGA. Stock ships 40 (20 dB) of a 0->80 range,
# i.e. half the available gain. Measured on device: 40->80 gives +20.4 dB raw and
# +14.6 dB after the Amazon ASP pipeline, with no clipping (raw peak 16% FS).
# 70 (35 dB) takes most of it while keeping ~14 dB of headroom for close speech.
# Leaves A_PGA_R_LINEIN alone: line-in has its own calibration.
# ponytail: sed over an extracted blob; fold into patches/ when vendor patching is unified.
if [[ -f "$PROP/etc/audio_init.sh" ]]; then
  sed -i 's/^A_PGA_L="40"$/A_PGA_L="70"/; s/^A_PGA_R="40"$/A_PGA_R="70"/' "$PROP/etc/audio_init.sh"
  grep -qx 'A_PGA_L="70"' "$PROP/etc/audio_init.sh" && grep -qx 'A_PGA_R="70"' "$PROP/etc/audio_init.sh" || {
    echo "ERROR: mic PGA patch did not apply to etc/audio_init.sh (stock format changed?)" >&2
    exit 1
  }
fi

cat > "$COMMON_OUT/mt8163-common-vendor.mk" <<'MK'
# MT8163 common blobs extracted from stock Biscuit system.img.
# No-GPU/headless path: intentionally no libGLES_mali, gralloc.mt8163.mali, or libgpu_aux.

PRODUCT_COPY_FILES += \
MK
for ((i = 0; i < ${#copy_files[@]}; i++)); do
  suffix=" \\"; [[ $i -eq $((${#copy_files[@]} - 1)) ]] && suffix=""
  printf '    %s%s\n' "${copy_files[$i]}" "$suffix" >> "$COMMON_OUT/mt8163-common-vendor.mk"
done

cat > "$COMMON_OUT/BoardConfigVendor.mk" <<'MK'
# BoardConfig vendor hook for MT8163 common blobs.
# Empty by design: current headless Biscuit build only needs PRODUCT_COPY_FILES.
MK

cat > "$BISCUIT_OUT/biscuit-vendor.mk" <<'MK'
# Biscuit-specific proprietary blobs.
# Empty by design: shared MT8163 blobs live in vendor/amazon/mt8163-common.
MK

cat > "$BISCUIT_OUT/blob-report.md" <<'MD'
# Biscuit blob report

Generated by `scripts/extract-biscuit-stock-blobs.sh` from stock Biscuit `system.img`.

Policy: no-GPU/headless. Excludes Mali EGL, Mali gralloc, and GPU helper blobs.
Audio/media: stock Amazon audio HAL wrapper plus stock audio tuning blobs; CM12/Google/ffmpeg codecs remain source/software, no stock MTK OMX blobs.
MD

if [[ -d "$REPO_ROOT/workspace/cm12/build" ]]; then
  "$REPO_ROOT/scripts/stage-tree.sh"
fi

echo "Extracted stock Biscuit blobs to $COMMON_OUT"
