#!/usr/bin/env bash
# Extract stock Biscuit non-GPU blobs from system.img into vendor/amazon/biscuit.
# Input: ext4 system.img from the Biscuit OTA, default workspace/extracted/biscuit-ota/system.img.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SYSTEM_IMG="${1:-$REPO_ROOT/workspace/extracted/biscuit-ota/system.img}"
OUT="$REPO_ROOT/workspace/vendor/amazon/biscuit"
PROP="$OUT/proprietary"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [[ ! -f "$SYSTEM_IMG" ]]; then
  echo "ERROR: system.img not found: $SYSTEM_IMG" >&2
  echo "Extract Biscuit OTA to workspace/extracted/biscuit-ota/system.img or pass a path." >&2
  exit 1
fi
command -v 7z >/dev/null || { echo "ERROR: 7z required" >&2; exit 1; }

rm -rf "$OUT"
mkdir -p "$PROP"

# Format: src[:dst]. dst defaults to src. Sources come from the Biscuit OTA system.img.
# No-GPU/headless set intentionally excludes Mali EGL/gralloc and GPU helper blobs.
entries=(
  lib/egl/egl.cfg
  lib/egl/libGLES_android.so
  lib/hw/gralloc.mt8163.so
  lib/hw/hwcomposer.mt8163.so
  lib/libGdmaScalerPipe.so
  lib/libbwc.so
  lib/libdpframework.so
  lib/libgralloc_extra.so
  lib/libgui_ext.so
  lib/libion_mtk.so
  lib/libm4u.so
  lib/libstlport.so
  lib/libui_ext.so
  lib64/egl/libGLES_android.so
  lib64/hw/gralloc.mt8163.so
  lib64/hw/hwcomposer.mt8163.so
  lib64/libbwc.so
  lib64/libdpframework.so
  lib64/libgralloc_extra.so
  lib64/libion_mtk.so
  lib64/libm4u.so
  lib64/libstlport.so
  bin/idme
  bin/devicetype_service
  lib/hw/keystore.mt8163.so
  lib/libtz_uree.so
  lib64/hw/keystore.mt8163.so
  lib64/libtz_uree.so
  bin/6620_launcher
  bin/wmt_loader
  etc/firmware/ROMv2_lm_patch_1_0_hdr.bin
  etc/firmware/ROMv2_lm_patch_1_1_hdr.bin
  etc/firmware/WIFI_RAM_CODE_8163
  etc/firmware/WMT_SOC.cfg
  etc/wifi/p2p_supplicant_overlay.conf
  etc/wifi/wpa_supplicant.conf
  etc/wifi/wpa_supplicant_overlay.conf
  bin/linker64
  lib64/libc.so
  lib64/libcutils.so
  lib64/liblog.so
  lib64/libm.so
  lib64/libsigchain.so
  lib64/libstdc++.so
  lib/libbt-vendor.so
  lib/libbluetooth_mtk.so
  lib/libnvram.so
  lib/libnvram_platform.so
  lib/libcustom_nvram.so

  # Stock audio HAL and its direct/tuning deps. Wrapper loads *_amazon via hw_get_module_by_class().
  lib/hw/audio.primary.mt8163.so:lib/hw/audio.primary_amazon.mt8163.so
  lib64/hw/audio.primary.mt8163.so:lib64/hw/audio.primary_amazon.mt8163.so
  lib/libasp.so
  lib/libaudiocompensationfilter.so
  lib/libaudiocomponentengine.so
  lib/libaudiocustparam.so
  lib/libaudiodcrflt.so
  lib/libaudiosetting.so
  lib/libbessound_hd_mtk.so
  lib/libblisrc.so
  lib/libblisrc32.so
  lib/libcvsd_mtk.so
  lib/libmsbc_mtk.so
  lib/libmtk_drvb.so
  lib/libmtklimiter.so
  lib/libmtkshifter.so
  lib/libspeech_enh_lib.so
  lib/libtinycompress.so
  lib/libtinyxml.so
  lib64/libasp.so
  lib64/libaudiocompensationfilter.so
  lib64/libaudiocomponentengine.so
  lib64/libaudiocustparam.so
  lib64/libaudiodcrflt.so
  lib64/libaudiosetting.so
  lib64/libbessound_hd_mtk.so
  lib64/libblisrc.so
  lib64/libblisrc32.so
  lib64/libcvsd_mtk.so
  lib64/libmsbc_mtk.so
  lib64/libmtk_drvb.so
  lib64/libmtklimiter.so
  lib64/libmtkshifter.so
  lib64/libspeech_enh_lib.so
  lib64/libtinycompress.so
  lib64/libtinyxml.so
)

copy_files=()
for entry in "${entries[@]}"; do
  src="${entry%%:*}"
  if [[ "$entry" == *:* ]]; then dst="${entry#*:}"; else dst="$src"; fi

  rm -rf "$TMP"/*
  # 7z returns non-zero on this ext4 image after extracting some files; trust the output file.
  7z x -y -o"$TMP" "$SYSTEM_IMG" "$src" >/dev/null 2>&1 || true
  if [[ ! -f "$TMP/$src" ]]; then
    echo "ERROR: missing in system.img: $src" >&2
    exit 1
  fi
  install -D -m 0644 "$TMP/$src" "$PROP/$dst"
  copy_files+=("vendor/amazon/biscuit/proprietary/$dst:system/$dst")
done

# Force software EGL. Stock has "0 1 mali" even though Biscuit is headless/no_gpu;
# CM12 bring-up must not load libGLES_mali.
printf '0 0 android\n' > "$PROP/lib/egl/egl.cfg"

cat > "$OUT/biscuit-vendor.mk" <<'MK'
# Biscuit blobs extracted from stock Biscuit system.img.
# No-GPU/headless path: intentionally no libGLES_mali, gralloc.mt8163.mali, or libgpu_aux.
# Audio path: CM12 builds audio.primary.mt8163 wrapper; stock HAL is copied as audio.primary_amazon.mt8163.

PRODUCT_COPY_FILES += \
MK
for ((i = 0; i < ${#copy_files[@]}; i++)); do
  suffix=" \\"; [[ $i -eq $((${#copy_files[@]} - 1)) ]] && suffix=""
  printf '    %s%s\n' "${copy_files[$i]}" "$suffix" >> "$OUT/biscuit-vendor.mk"
done

cat > "$OUT/blob-report.md" <<'MD'
# Biscuit blob report

Generated by `workspace/scripts/extract-biscuit-stock-blobs.sh` from stock Biscuit `system.img`.

Policy: no-GPU/headless. Excludes Mali EGL, Mali gralloc, and GPU helper blobs.
Audio: stock OTA HAL is copied as `audio.primary_amazon.mt8163.so`; CM12 builds the wrapper `audio.primary.mt8163.so`.
MD

if [[ -d "$REPO_ROOT/workspace/cm12/build" ]]; then
  "$REPO_ROOT/workspace/scripts/stage-tree.sh"
fi

echo "Extracted stock Biscuit no-GPU/audio blobs to $OUT"
